[package]
name = "qtwallset"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.32"
env_logger = "0.11.7"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
shellexpand = "3.1.0"
